AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: "An example Golang AWS SAM Lambda project"

Globals:
  Function:
    Timeout: 5
    MemorySize: 256

Resources:
  AwsLambdaExample:
    Type: "AWS::Serverless::Function"
    Properties:
      CodeUri: build/lambda_app.zip
      Handler: bootstrap
      Runtime: provided.al2
      PackageType: Zip
      Architectures:
        - arm64
      Events:
        CatchAll:
          Type: Api
          Properties:
            Path: /api/test
            Method: GET
      Environment:
        Variables:
          PARAM1: EXAMPLE_VALUE
